site_name: hk
site_author: Hrushikesh Dokala
site_url : https://hk669.github.io/dsa/
repo_url: https://github.com/Hk669/DSA
repo_name: Hk669/DSA
edit_uri: edit/main/docs
nav:
  - Home:
    - Home: index.md
    - Data Structures: algorithms.md
    - Contribution: contribution.md
    - Blog: https://blog.hrushikesh.xyz
  - Data Structures:
    - Introduction: algorithms.md
    - Contribution: contribution.md
    - Blog: https://blog.hrushikesh.xyz
  - Blog: https://blog.hrushikesh.xyz
  # - Arrays: arrays.md
theme:
  name: material
  logo: assets/favicon.svg
  icon:
    repo: fontawesome/brands/git-alt
  favicon: assets/favicon.svg
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default 
      primary: deep blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto 
    code: Roboto Mono
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/hrushikeshhhh
    - icon: fontawesome/brands/github
      link: https://github.com/Hk669
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/hrushikeshdokala/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/hkeshhk
  generator: false
plugins: 
  - mkdocstrings
  - search
copyright: Copyright &copy; 2024 Hrushikesh Dokala