name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name:  Install Dependencies
        run: pip install -r requirements.txt

      - name: Build and Deploy
        run: |
          mkdocs build
          mkdocs gh-deploy --force


      # - name: Deploy to pages
      #   run: peaceiris/actions-gh-pages@v3
      #   with:
      #     deploy_key: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./site
